# Generated by Django 5.2.4 on 2025-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatlabExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='courses/matlab/exp_imgs')),
                ('blog_file', models.FileField(upload_to='courses/matlab/exp_detail')),
                ('exp_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MatlabMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='courses/matlab/materials')),
            ],
        ),
    ]
