# Generated by Django 5.2.4 on 2025-08-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_no', models.CharField(max_length=2)),
                ('slide_no', models.CharField(max_length=2)),
                ('img', models.ImageField(upload_to='courses/matlab/exp_outputs')),
            ],
        ),
    ]
