# Generated by Django 5.1.6 on 2025-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images')),
                ('git', models.URLField(blank=True, max_length=255, null=True)),
                ('lkdn', models.URLField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
