# Generated by Django 5.1.6 on 2025-04-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='s_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
