# Generated by Django 5.1.6 on 2025-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0003_alter_team_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='apps_images')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('s_id', models.CharField(blank=True, max_length=15, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
