# Generated by Django 5.1.6 on 2025-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0004_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('s_id', models.CharField(blank=True, max_length=15, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='game_images')),
                ('git_link', models.URLField(blank=True, max_length=300, null=True)),
                ('play_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
