# Generated by Django 5.1.6 on 2025-04-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0005_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=30, null=True)),
                ('speaker', models.CharField(blank=True, max_length=30, null=True)),
                ('speaker_details', models.TextField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('meet_url', models.URLField(blank=True, null=True)),
                ('vid_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
