# Generated by Django 5.1.6 on 2025-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meet_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vid_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
