# Generated by Django 5.1.6 on 2025-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0007_alter_event_meet_url_alter_event_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog', models.FileField(blank=True, null=True, upload_to='blogs')),
            ],
        ),
    ]
