# Generated by Django 5.2.4 on 2025-08-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0009_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
                ('article_link', models.URLField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
