# Generated by Django 5.2.4 on 2025-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0010_careerchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerchoice',
            name='article_link',
        ),
        migrations.RemoveField(
            model_name='careerchoice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='careerchoice',
            name='video_link',
        ),
        migrations.AddField(
            model_name='careerchoice',
            name='data',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='careerchoice',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
