# Generated by Django 5.2.4 on 2025-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0011_remove_careerchoice_article_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=60)),
                ('venue', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=300)),
                ('prizes', models.CharField(max_length=100)),
                ('moderators', models.CharField(max_length=200)),
                ('leaderboard_url', models.URLField(blank=True, max_length=500, null=True)),
                ('discord_url', models.URLField(default='https://discord.gg/ChE5k7BNSe', max_length=500)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
