# Generated by Django 5.2.4 on 2025-08-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0012_hackathon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='details',
            field=models.TextField(max_length=500),
        ),
    ]
