# Generated by Django 5.2.4 on 2025-08-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hub', '0013_alter_hackathon_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('blog', models.FileField(blank=True, null=True, upload_to='blogs')),
            ],
        ),
    ]
